---
- name: Use community.general collection on Ubuntu
  hosts: webservers
  become: yes  # Required for package installation

  tasks:
    - name: Display system information
      community.general.content:
        # Direct module parameters without variables
        path: /etc/os-release
        register: content_output

    - name: Print OS name and version
      debug:
        msg: "OS Name: {{ content_output.stdout.split('=')[1].strip() }}\nOS Version: {{ content_output.stdout.split('=')[1].split()[0] }}"

    - name: Download content from URL
      community.general.content:
        src: https://raw.githubusercontent.com/ansible/ansible/devel/docsite/en_US/intro/getting_started.rst
        dest: /tmp/getting_started.rst
        mode: 0644  # Set file permissions



- name: Install Docker and run Nginx container
  hosts: webservers
  become: yes
  tasks:
    - name: Install Docker
      community.general.package:
        name: docker.io
        state: present
        # module to install Docker 

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started
        enabled: yes
        # Ensure the Docker service is started and enabled to manage Docker containers.

    - name: Run Nginx container
      community.docker.docker_container:
        name: nginx-1.1
        image: nginx
        ports:
          - "80:80"
        state: started
        # module to run an Nginx container named nginx

    - name: Verify Nginx container status
      community.docker.docker_container_info:
        name: nginx-1.1
      register: nginx_container_info

    - name: Check if Nginx container is running
      assert:
        that:
          - nginx_container_info.State == 'running'

    - name: Verify connection to Nginx
      uri:
        url: "http://localhost:80"
        status_code: 200
      register: nginx_response

    - name: Print Nginx response
      debug:
        var: nginx_response



