---
- name: Example playbook to demonstrate ansible_hostname vs inventory_hostname
  hosts: webservers
  gather_facts: yes

  tasks:
    - name: Display inventory_hostname
      debug:
        msg: "inventory_hostname: {{ inventory_hostname }}"

    - name: Display ansible_hostname
      debug:
        msg: "ansible_hostname: {{ ansible_hostname }}"
