---
- name: Gather and display OS family
  hosts: all
  gather_facts: yes
  tasks:
    - name: Display the OS family
      debug:
        msg: "The OS family is {{ ansible_os_family }}"


- name: Reboot Servers Example
  hosts: all
  become: yes  # Ensure that the playbook runs with elevated privileges
  tasks:
    - name: Apply updates and reboot
      block:
        - name: Update all packages
          apt:
            update_cache: yes
            upgrade: dist
          when: ansible_os_family == 'Debian'

        - name: Reboot the server
          reboot:
            msg: "Reboot initiated by Ansible for updates"
            reboot_timeout: 300
            post_reboot_delay: 30

        - name: Ensure the server is up and running
          command: uptime
          register: uptime_result

        - name: Print uptime
          debug:
            var: uptime_result.stdout

      when: ansible_os_family == 'Debian'  # Adjust this condition as needed for your environment
