---
- name: Demonstrate Hardlink with Ansible
  hosts: webservers
  become: yes
  
  tasks:
    - name: Create a file
      ansible.builtin.file:
        path: /tmp/source_file.txt
        state: touch
        mode: '0644'
        # Optionally, set initial content
        # content: "This is the source file.\n"

    - name: Create a hard link to the file
      ansible.builtin.file:
        src: /tmp/source_file.txt
        dest: /tmp/hardlink_to_source
        state: link

    - name: Verify existence of the hard link
      ansible.builtin.stat:
        path: /tmp/hardlink_to_source
      register: hardlink_info

    - debug:
        msg: "Hard link exists: {{ hardlink_info.stat.exists }}"

    - name: Remove the hard link
      ansible.builtin.file:
        path: /tmp/hardlink_to_source
        state: absent

    - name: Verify removal of the hard link
      ansible.builtin.stat:
        path: /tmp/hardlink_to_source
      register: removed_link_info

    - debug:
        msg: "Hard link removed: {{ not removed_link_info.stat.exists }}"
