---
- name: Create and Verify Soft Link for CPU/Memory Usage
  hosts: webservers 
  
  tasks:
    - name: Create a symbolic link to /proc/cpuinfo
      ansible.builtin.file:
        src: /proc/cpuinfo
        dest: /tmp/cpuinfo_link
        state: link
        
    - name: Verify symbolic link creation
      ansible.builtin.stat:
        path: /tmp/cpuinfo_link
      register: link_stats
      
    - name: Print symbolic link verification result
      ansible.builtin.debug:
        msg: "Symbolic link exists: {{ link_stats.stat.islnk }}"

    - name: Read content of the symbolic link (CPU info)
      ansible.builtin.shell: cat /tmp/cpuinfo_link
      register: cpuinfo_content
      
    - name: Print CPU info
      ansible.builtin.debug:
        msg: "{{ cpuinfo_content.stdout }}"
        
    - name: Create a symbolic link to /proc/meminfo
      ansible.builtin.file:
        src: /proc/meminfo
        dest: /tmp/meminfo_link
        state: link
        
    - name: Verify symbolic link creation for memory info
      ansible.builtin.stat:
        path: /tmp/meminfo_link
      register: meminfo_link_stats
      
    - name: Print symbolic link verification result for memory info
      ansible.builtin.debug:
        msg: "Symbolic link exists: {{ meminfo_link_stats.stat.islnk }}"

    - name: Read content of the symbolic link (Memory info)
      ansible.builtin.shell: cat /tmp/meminfo_link
      register: meminfo_content
      
    - name: Print Memory info
      ansible.builtin.debug:
        msg: "{{ meminfo_content.stdout }}"
